// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	ExamID pgtype.UUID
}

type Exam struct {
	ID        pgtype.UUID
	SuperID   pgtype.UUID
	Name      string
	Location  string
	Organizer string
	Begin     pgtype.Date
	Finish    pgtype.Date
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Result struct {
	ID        pgtype.UUID
	ShooterID pgtype.UUID
	Status    bool
	Stage     interface{}
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Scorer struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	ExamID pgtype.UUID
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type Shooter struct {
	ID        pgtype.UUID
	ExamID    pgtype.UUID
	Name      string
	ImagePath string
	Province  string
	Club      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Stage0Result struct {
	ID        pgtype.UUID
	ResultID  pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Stage1Result struct {
	ID        pgtype.UUID
	ResultID  pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Stage2Result struct {
	ID        pgtype.UUID
	ResultID  pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Stage3Result struct {
	ID        pgtype.UUID
	ResultID  pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Stage4Result struct {
	ID        pgtype.UUID
	ResultID  pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Stage5Result struct {
	ID        pgtype.UUID
	ResultID  pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Stage6Result struct {
	ID        pgtype.UUID
	ResultID  pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Super struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Password  string
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
