// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// untuk ngebuat admin (super role) TODO: return sebanyak get admin by id
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (CreateAdminRow, error)
	// untuk membuat exam (super role)
	CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error)
	// (all role)
	CreateResult(ctx context.Context, shooterID pgtype.UUID) (Result, error)
	// untuk ngebuat scorer (admin-super role) TODO: return sebanyak get scorer by id
	CreateScorer(ctx context.Context, arg CreateScorerParams) (CreateScorerRow, error)
	// membuat shooter baru (admin-super role)
	CreateShooter(ctx context.Context, arg CreateShooterParams) (Shooter, error)
	// (all role)
	CreateStage0(ctx context.Context, resultID pgtype.UUID) (Stage0Result, error)
	CreateStage1(ctx context.Context, resultID pgtype.UUID) (CreateStage1Row, error)
	CreateStage1try2(ctx context.Context, id pgtype.UUID) (CreateStage1try2Row, error)
	CreateStage2(ctx context.Context, resultID pgtype.UUID) (CreateStage2Row, error)
	CreateStage2try2(ctx context.Context, id pgtype.UUID) (CreateStage2try2Row, error)
	CreateStage3(ctx context.Context, resultID pgtype.UUID) (CreateStage3Row, error)
	CreateStage3try2(ctx context.Context, id pgtype.UUID) (CreateStage3try2Row, error)
	CreateStage4(ctx context.Context, resultID pgtype.UUID) (CreateStage4Row, error)
	CreateStage4try2(ctx context.Context, id pgtype.UUID) (CreateStage4try2Row, error)
	CreateStage5(ctx context.Context, resultID pgtype.UUID) (CreateStage5Row, error)
	CreateStage5try2(ctx context.Context, id pgtype.UUID) (CreateStage5try2Row, error)
	CreateStage6(ctx context.Context, resultID pgtype.UUID) (CreateStage6Row, error)
	CreateStage6try2(ctx context.Context, id pgtype.UUID) (CreateStage6try2Row, error)
	// untuk menghapus exam (super role)
	DeleteExam(ctx context.Context, id pgtype.UUID) error
	// (admin-super role) dibuat by id
	DeleteResult(ctx context.Context, id pgtype.UUID) error
	// untuk menghapus shooter berdasarkan id (admin-super role)
	DeleteShooter(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage0(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage1(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage1try2(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage2(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage2try2(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage3(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage3try2(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage4(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage4try2(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage5(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage5try2(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage6(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	DeleteStage6try2(ctx context.Context, id pgtype.UUID) error
	// dipake untuk delete user
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	FinishStage0(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	FinishStage1(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	FinishStage2(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	FinishStage3(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	FinishStage4(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	FinishStage5(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	FinishStage6(ctx context.Context, id pgtype.UUID) error
	// untuk ngambil data akun admin berdasarkan id (super role)
	GetAdminById(ctx context.Context, id pgtype.UUID) (GetAdminByIdRow, error)
	// untuk ngambil data lengkap admin berdasarkan user id (admin role)
	GetAdminByUserId(ctx context.Context, userID pgtype.UUID) (GetAdminByUserIdRow, error)
	// untuk ngambil data display admin berdasarkan username (admin role)
	GetAdminByUsername(ctx context.Context, username string) (GetAdminByUsernameRow, error)
	// untuk ngambil data relasi admin dan relasi exam berdasarkan user id (all role)
	GetAdminExamRelationByUserId(ctx context.Context, userID pgtype.UUID) (GetAdminExamRelationByUserIdRow, error)
	// untuk ngambil data relasi admin berdasarkan id (all role)
	GetAdminRelationById(ctx context.Context, id pgtype.UUID) (Admin, error)
	// untuk ngambil data akun seluruh admin dalam satu exam (super role)
	GetAdminsByExamId(ctx context.Context, examID pgtype.UUID) ([]GetAdminsByExamIdRow, error)
	// untuk ngambil data display seluruh admin (all role)
	GetAllAdmins(ctx context.Context) ([]GetAllAdminsRow, error)
	// untuk mengambil seluruh exam (super role)
	GetAllExams(ctx context.Context) ([]GetAllExamsRow, error)
	// untuk ngambil data display seluruh scorer (all role)
	GetAllScorers(ctx context.Context) ([]GetAllScorersRow, error)
	// untuk mengambil seluruh shooter (admin-super role)
	GetAllShooters(ctx context.Context) ([]GetAllShootersRow, error)
	// untuk ngambil data display seluruh super admin (all role)
	GetAllSupers(ctx context.Context) ([]GetAllSupersRow, error)
	// untuk mengambil satu data exam (super role)
	GetExamById(ctx context.Context, id pgtype.UUID) (Exam, error)
	// untuk mengambil exam berdasarkan nama untuk cek nama sudah dipakai blum (super role)
	GetExamByName(ctx context.Context, name string) (pgtype.UUID, error)
	// untuk mengambil data relasi exam (all role)
	GetExamRelationById(ctx context.Context, id pgtype.UUID) (GetExamRelationByIdRow, error)
	// untuk mengambil seluruh exam (super role)
	GetExamsBySuperId(ctx context.Context, superID pgtype.UUID) ([]GetExamsBySuperIdRow, error)
	GetResultById(ctx context.Context, id pgtype.UUID) (Result, error)
	GetResultRelationAndStatusByShooterId(ctx context.Context, shooterID pgtype.UUID) (GetResultRelationAndStatusByShooterIdRow, error)
	// untuk ngambil data akun scorer berdasarkan id (admin-super role)
	GetScorerById(ctx context.Context, id pgtype.UUID) (GetScorerByIdRow, error)
	// untuk ngambil data lengkap scorer berdasarkan user id (scorer role)
	GetScorerByUserId(ctx context.Context, userID pgtype.UUID) (GetScorerByUserIdRow, error)
	// untuk ngambil data display scorer berdasarkan username (scorer role)
	GetScorerByUsername(ctx context.Context, username string) (GetScorerByUsernameRow, error)
	// untuk ngambil data relasi scorer berdasarkan id (all role)
	GetScorerRelationById(ctx context.Context, id pgtype.UUID) (Scorer, error)
	// untuk ngambil data relasi scorer berdasarkan user id (all role)
	GetScorerRelationByUserId(ctx context.Context, userID pgtype.UUID) (GetScorerRelationByUserIdRow, error)
	// untuk ngambil data akun seluruh scorer dalam satu exam (admin-super role)
	GetScorersByExamId(ctx context.Context, examID pgtype.UUID) ([]GetScorersByExamIdRow, error)
	// untuk mengambil shooter berdasarkan exam_id (admin-super role)
	GetShooterByExamId(ctx context.Context, examID pgtype.UUID) ([]GetShooterByExamIdRow, error)
	// untuk mengambil shooter berdasarkan id (admin-super role)
	GetShooterById(ctx context.Context, id pgtype.UUID) (Shooter, error)
	// untuk mengambil relasi shooter berdasarkan id (all role)
	GetShooterRelationById(ctx context.Context, id pgtype.UUID) (GetShooterRelationByIdRow, error)
	// untuk mengambil shooter berdasarkan scorer_id (all role)
	GetShootersByScorerId(ctx context.Context, scorerID pgtype.UUID) ([]GetShootersByScorerIdRow, error)
	// (all role)
	GetStage0ById(ctx context.Context, id pgtype.UUID) (Stage0Result, error)
	// (all role)
	GetStage0RelationByResultId(ctx context.Context, resultID pgtype.UUID) (GetStage0RelationByResultIdRow, error)
	GetStage0Status(ctx context.Context, id pgtype.UUID) (Stage0Status, error)
	// (all role)
	GetStage1ById(ctx context.Context, id pgtype.UUID) (GetStage1ByIdRow, error)
	// (all role)
	GetStage1RelationByResultId(ctx context.Context, resultID pgtype.UUID) (GetStage1RelationByResultIdRow, error)
	GetStage1try1Status(ctx context.Context, id pgtype.UUID) (Stage13Status, error)
	// (all role)
	GetStage1try2ExistById(ctx context.Context, id pgtype.UUID) (bool, error)
	// (all role)
	GetStage1try2Status(ctx context.Context, id pgtype.UUID) (Stage13Status, error)
	// (all role)
	GetStage2ById(ctx context.Context, id pgtype.UUID) (GetStage2ByIdRow, error)
	// (all role)
	GetStage2RelationByResultId(ctx context.Context, resultID pgtype.UUID) (GetStage2RelationByResultIdRow, error)
	GetStage2try1Status(ctx context.Context, id pgtype.UUID) (Stage246Status, error)
	// (all role)
	GetStage2try2ExistById(ctx context.Context, id pgtype.UUID) (bool, error)
	// (all role)
	GetStage2try2Status(ctx context.Context, id pgtype.UUID) (Stage246Status, error)
	// (all role)
	GetStage3ById(ctx context.Context, id pgtype.UUID) (GetStage3ByIdRow, error)
	// (all role)
	GetStage3RelationByResultId(ctx context.Context, resultID pgtype.UUID) (GetStage3RelationByResultIdRow, error)
	GetStage3try1Status(ctx context.Context, id pgtype.UUID) (Stage13Status, error)
	// (all role)
	GetStage3try2ExistById(ctx context.Context, id pgtype.UUID) (bool, error)
	// (all role)
	GetStage3try2Status(ctx context.Context, id pgtype.UUID) (Stage13Status, error)
	// (all role)
	GetStage4ById(ctx context.Context, id pgtype.UUID) (GetStage4ByIdRow, error)
	// (all role)
	GetStage4RelationByResultId(ctx context.Context, resultID pgtype.UUID) (GetStage4RelationByResultIdRow, error)
	GetStage4try1Status(ctx context.Context, id pgtype.UUID) (Stage246Status, error)
	// (all role)
	GetStage4try2ExistById(ctx context.Context, id pgtype.UUID) (bool, error)
	// (all role)
	GetStage4try2Status(ctx context.Context, id pgtype.UUID) (Stage246Status, error)
	// (all role)
	GetStage5ById(ctx context.Context, id pgtype.UUID) (GetStage5ByIdRow, error)
	// (all role)
	GetStage5RelationByResultId(ctx context.Context, resultID pgtype.UUID) (GetStage5RelationByResultIdRow, error)
	GetStage5try1Status(ctx context.Context, id pgtype.UUID) (Stage5Status, error)
	// (all role)
	GetStage5try2ExistById(ctx context.Context, id pgtype.UUID) (bool, error)
	// (all role)
	GetStage5try2Status(ctx context.Context, id pgtype.UUID) (Stage5Status, error)
	// (all role)
	GetStage6ById(ctx context.Context, id pgtype.UUID) (GetStage6ByIdRow, error)
	// (all role)
	GetStage6RelationByResultId(ctx context.Context, resultID pgtype.UUID) (GetStage6RelationByResultIdRow, error)
	GetStage6try1Status(ctx context.Context, id pgtype.UUID) (Stage246Status, error)
	// (all role)
	GetStage6try2ExistById(ctx context.Context, id pgtype.UUID) (bool, error)
	// (all role)
	GetStage6try2Status(ctx context.Context, id pgtype.UUID) (Stage246Status, error)
	// untuk ngambil data lengkap super admin berdasarkan user id (super role)
	GetSuperByUserId(ctx context.Context, userID pgtype.UUID) (GetSuperByUserIdRow, error)
	// untuk ngambil data display super admin berdasarkan username (super role)
	GetSuperByUsername(ctx context.Context, username string) (GetSuperByUsernameRow, error)
	// untuk ngambil data relasi super admin berdasarkan user id (all role)
	GetSuperRelationByUserId(ctx context.Context, userID pgtype.UUID) (Super, error)
	// dipake untuk mengecek username ketika create user baru
	GetUserByUsername(ctx context.Context, username string) (pgtype.UUID, error)
	// untuk update data akun admin (super role)
	UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (UpdateAdminRow, error)
	// low prio
	UpdateAdminName(ctx context.Context, arg UpdateAdminNameParams) (pgtype.UUID, error)
	// low prio
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) (pgtype.UUID, error)
	// untuk memperbarui exam (super role)
	UpdateExam(ctx context.Context, arg UpdateExamParams) (UpdateExamRow, error)
	// untuk mengubah status exam (super role)
	UpdateExamStatus(ctx context.Context, id pgtype.UUID) (bool, error)
	// (admin-super role) dibuat by id
	UpdateResult(ctx context.Context, arg UpdateResultParams) (Result, error)
	// (scorer role) dibuat by id, utk update stage
	UpdateResultNextStage(ctx context.Context, arg UpdateResultNextStageParams) error
	// (admin-super role) utk edge case kalo delete stage yang terakir, mundurin ke stage sebelum
	UpdateResultStage(ctx context.Context, arg UpdateResultStageParams) error
	// untuk update data akun admin (super role) TODO: return sebanyak get admin by id
	UpdateScorer(ctx context.Context, arg UpdateScorerParams) (UpdateScorerRow, error)
	// low prio
	UpdateScorerName(ctx context.Context, arg UpdateScorerNameParams) (pgtype.UUID, error)
	// low prio
	UpdateScorerPassword(ctx context.Context, arg UpdateScorerPasswordParams) (pgtype.UUID, error)
	// untuk mengupdate shooter berdasarkan id (admin-super role)
	UpdateShooter(ctx context.Context, arg UpdateShooterParams) (UpdateShooterRow, error)
	// untuk mengupdate foto shooter berdasarkan id (admin-super role)
	UpdateShooterImage(ctx context.Context, arg UpdateShooterImageParams) (Shooter, error)
	// (admin-super role)
	UpdateStage0(ctx context.Context, arg UpdateStage0Params) (UpdateStage0Row, error)
	// (scorer role)
	UpdateStage0Checkmarks(ctx context.Context, arg UpdateStage0CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage0FinishFailed(ctx context.Context, arg UpdateStage0FinishFailedParams) error
	// (scorer role)
	UpdateStage0FinishSuccess(ctx context.Context, arg UpdateStage0FinishSuccessParams) error
	// (scorer role)
	UpdateStage0NextSeries(ctx context.Context, arg UpdateStage0NextSeriesParams) error
	// (scorer role)
	UpdateStage0Series1(ctx context.Context, arg UpdateStage0Series1Params) (string, error)
	// (scorer role)
	UpdateStage0Series2(ctx context.Context, arg UpdateStage0Series2Params) (string, error)
	// (scorer role)
	UpdateStage0Series3(ctx context.Context, arg UpdateStage0Series3Params) (string, error)
	// (scorer role)
	UpdateStage0Series4(ctx context.Context, arg UpdateStage0Series4Params) (string, error)
	// (scorer role)
	UpdateStage0Series5(ctx context.Context, arg UpdateStage0Series5Params) (string, error)
	// (admin-super role)
	UpdateStage0Signs(ctx context.Context, arg UpdateStage0SignsParams) (UpdateStage0SignsRow, error)
	// (scorer role)
	UpdateStage1NextTry(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	UpdateStage1Signs(ctx context.Context, arg UpdateStage1SignsParams) (UpdateStage1SignsRow, error)
	// (admin-super role)
	UpdateStage1try1(ctx context.Context, arg UpdateStage1try1Params) (UpdateStage1try1Row, error)
	// (scorer role)
	UpdateStage1try1Checkmarks(ctx context.Context, arg UpdateStage1try1CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage1try1FinishFailed(ctx context.Context, arg UpdateStage1try1FinishFailedParams) error
	// (scorer role)
	UpdateStage1try1FinishSuccess(ctx context.Context, arg UpdateStage1try1FinishSuccessParams) error
	// (scorer role)
	UpdateStage1try1NextNo(ctx context.Context, arg UpdateStage1try1NextNoParams) error
	// (scorer role)
	UpdateStage1try1No1(ctx context.Context, arg UpdateStage1try1No1Params) (string, error)
	// (scorer role)
	UpdateStage1try1No2(ctx context.Context, arg UpdateStage1try1No2Params) (string, error)
	// (scorer role)
	UpdateStage1try1No3(ctx context.Context, arg UpdateStage1try1No3Params) (string, error)
	// (scorer role)
	UpdateStage1try1No4(ctx context.Context, arg UpdateStage1try1No4Params) (string, error)
	// (scorer role)
	UpdateStage1try1No5(ctx context.Context, arg UpdateStage1try1No5Params) (string, error)
	// (scorer role)
	UpdateStage1try1No6(ctx context.Context, arg UpdateStage1try1No6Params) (string, error)
	// (admin-super role)
	UpdateStage1try2(ctx context.Context, arg UpdateStage1try2Params) (UpdateStage1try2Row, error)
	// (scorer role)
	UpdateStage1try2Checkmarks(ctx context.Context, arg UpdateStage1try2CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage1try2FinishFailed(ctx context.Context, arg UpdateStage1try2FinishFailedParams) error
	// (scorer role)
	UpdateStage1try2FinishSuccess(ctx context.Context, arg UpdateStage1try2FinishSuccessParams) error
	// (scorer role)
	UpdateStage1try2NextNo(ctx context.Context, arg UpdateStage1try2NextNoParams) error
	// (scorer role)
	UpdateStage1try2No1(ctx context.Context, arg UpdateStage1try2No1Params) (string, error)
	// (scorer role)
	UpdateStage1try2No2(ctx context.Context, arg UpdateStage1try2No2Params) (string, error)
	// (scorer role)
	UpdateStage1try2No3(ctx context.Context, arg UpdateStage1try2No3Params) (string, error)
	// (scorer role)
	UpdateStage1try2No4(ctx context.Context, arg UpdateStage1try2No4Params) (string, error)
	// (scorer role)
	UpdateStage1try2No5(ctx context.Context, arg UpdateStage1try2No5Params) (string, error)
	// (scorer role)
	UpdateStage1try2No6(ctx context.Context, arg UpdateStage1try2No6Params) (string, error)
	// (scorer role)
	UpdateStage2NextTry(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	UpdateStage2Signs(ctx context.Context, arg UpdateStage2SignsParams) (UpdateStage2SignsRow, error)
	// (admin-super role)
	UpdateStage2try1(ctx context.Context, arg UpdateStage2try1Params) (UpdateStage2try1Row, error)
	// (scorer role)
	UpdateStage2try1Checkmarks(ctx context.Context, arg UpdateStage2try1CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage2try1FinishFailed(ctx context.Context, arg UpdateStage2try1FinishFailedParams) error
	// (scorer role)
	UpdateStage2try1FinishSuccess(ctx context.Context, arg UpdateStage2try1FinishSuccessParams) error
	// (scorer role)
	UpdateStage2try1NextNo(ctx context.Context, arg UpdateStage2try1NextNoParams) error
	// (scorer role)
	UpdateStage2try1No1(ctx context.Context, arg UpdateStage2try1No1Params) (string, error)
	// (scorer role)
	UpdateStage2try1No2(ctx context.Context, arg UpdateStage2try1No2Params) (string, error)
	// (scorer role)
	UpdateStage2try1No3(ctx context.Context, arg UpdateStage2try1No3Params) (string, error)
	// (admin-super role)
	UpdateStage2try2(ctx context.Context, arg UpdateStage2try2Params) (UpdateStage2try2Row, error)
	// (scorer role)
	UpdateStage2try2Checkmarks(ctx context.Context, arg UpdateStage2try2CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage2try2FinishFailed(ctx context.Context, arg UpdateStage2try2FinishFailedParams) error
	// (scorer role)
	UpdateStage2try2FinishSuccess(ctx context.Context, arg UpdateStage2try2FinishSuccessParams) error
	// (scorer role)
	UpdateStage2try2NextNo(ctx context.Context, arg UpdateStage2try2NextNoParams) error
	// (scorer role)
	UpdateStage2try2No1(ctx context.Context, arg UpdateStage2try2No1Params) (string, error)
	// (scorer role)
	UpdateStage2try2No2(ctx context.Context, arg UpdateStage2try2No2Params) (string, error)
	// (scorer role)
	UpdateStage2try2No3(ctx context.Context, arg UpdateStage2try2No3Params) (string, error)
	// (scorer role)
	UpdateStage3NextTry(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	UpdateStage3Signs(ctx context.Context, arg UpdateStage3SignsParams) (UpdateStage3SignsRow, error)
	// (admin-super role)
	UpdateStage3try1(ctx context.Context, arg UpdateStage3try1Params) (UpdateStage3try1Row, error)
	// (scorer role)
	UpdateStage3try1Checkmarks(ctx context.Context, arg UpdateStage3try1CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage3try1FinishFailed(ctx context.Context, arg UpdateStage3try1FinishFailedParams) error
	// (scorer role)
	UpdateStage3try1FinishSuccess(ctx context.Context, arg UpdateStage3try1FinishSuccessParams) error
	// (scorer role)
	UpdateStage3try1NextNo(ctx context.Context, arg UpdateStage3try1NextNoParams) error
	// (scorer role)
	UpdateStage3try1No1(ctx context.Context, arg UpdateStage3try1No1Params) (string, error)
	// (scorer role)
	UpdateStage3try1No2(ctx context.Context, arg UpdateStage3try1No2Params) (string, error)
	// (scorer role)
	UpdateStage3try1No3(ctx context.Context, arg UpdateStage3try1No3Params) (string, error)
	// (scorer role)
	UpdateStage3try1No4(ctx context.Context, arg UpdateStage3try1No4Params) (string, error)
	// (scorer role)
	UpdateStage3try1No5(ctx context.Context, arg UpdateStage3try1No5Params) (string, error)
	// (scorer role)
	UpdateStage3try1No6(ctx context.Context, arg UpdateStage3try1No6Params) (string, error)
	// (admin-super role)
	UpdateStage3try2(ctx context.Context, arg UpdateStage3try2Params) (UpdateStage3try2Row, error)
	// (scorer role)
	UpdateStage3try2Checkmarks(ctx context.Context, arg UpdateStage3try2CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage3try2FinishFailed(ctx context.Context, arg UpdateStage3try2FinishFailedParams) error
	// (scorer role)
	UpdateStage3try2FinishSuccess(ctx context.Context, arg UpdateStage3try2FinishSuccessParams) error
	// (scorer role)
	UpdateStage3try2NextNo(ctx context.Context, arg UpdateStage3try2NextNoParams) error
	// (scorer role)
	UpdateStage3try2No1(ctx context.Context, arg UpdateStage3try2No1Params) (string, error)
	// (scorer role)
	UpdateStage3try2No2(ctx context.Context, arg UpdateStage3try2No2Params) (string, error)
	// (scorer role)
	UpdateStage3try2No3(ctx context.Context, arg UpdateStage3try2No3Params) (string, error)
	// (scorer role)
	UpdateStage3try2No4(ctx context.Context, arg UpdateStage3try2No4Params) (string, error)
	// (scorer role)
	UpdateStage3try2No5(ctx context.Context, arg UpdateStage3try2No5Params) (string, error)
	// (scorer role)
	UpdateStage3try2No6(ctx context.Context, arg UpdateStage3try2No6Params) (string, error)
	// (scorer role)
	UpdateStage4NextTry(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	UpdateStage4Signs(ctx context.Context, arg UpdateStage4SignsParams) (UpdateStage4SignsRow, error)
	// (admin-super role)
	UpdateStage4try1(ctx context.Context, arg UpdateStage4try1Params) (UpdateStage4try1Row, error)
	// (scorer role)
	UpdateStage4try1Checkmarks(ctx context.Context, arg UpdateStage4try1CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage4try1FinishFailed(ctx context.Context, arg UpdateStage4try1FinishFailedParams) error
	// (scorer role)
	UpdateStage4try1FinishSuccess(ctx context.Context, arg UpdateStage4try1FinishSuccessParams) error
	// (scorer role)
	UpdateStage4try1NextNo(ctx context.Context, arg UpdateStage4try1NextNoParams) error
	// (scorer role)
	UpdateStage4try1No1(ctx context.Context, arg UpdateStage4try1No1Params) (string, error)
	// (scorer role)
	UpdateStage4try1No2(ctx context.Context, arg UpdateStage4try1No2Params) (string, error)
	// (scorer role)
	UpdateStage4try1No3(ctx context.Context, arg UpdateStage4try1No3Params) (string, error)
	// (admin-super role)
	UpdateStage4try2(ctx context.Context, arg UpdateStage4try2Params) (UpdateStage4try2Row, error)
	// (scorer role)
	UpdateStage4try2Checkmarks(ctx context.Context, arg UpdateStage4try2CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage4try2FinishFailed(ctx context.Context, arg UpdateStage4try2FinishFailedParams) error
	// (scorer role)
	UpdateStage4try2FinishSuccess(ctx context.Context, arg UpdateStage4try2FinishSuccessParams) error
	// (scorer role)
	UpdateStage4try2NextNo(ctx context.Context, arg UpdateStage4try2NextNoParams) error
	// (scorer role)
	UpdateStage4try2No1(ctx context.Context, arg UpdateStage4try2No1Params) (string, error)
	// (scorer role)
	UpdateStage4try2No2(ctx context.Context, arg UpdateStage4try2No2Params) (string, error)
	// (scorer role)
	UpdateStage4try2No3(ctx context.Context, arg UpdateStage4try2No3Params) (string, error)
	// (scorer role)
	UpdateStage5NextTry(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	UpdateStage5Signs(ctx context.Context, arg UpdateStage5SignsParams) (UpdateStage5SignsRow, error)
	// (admin-super role)
	UpdateStage5try1(ctx context.Context, arg UpdateStage5try1Params) (UpdateStage5try1Row, error)
	// (scorer role)
	UpdateStage5try1Checkmarks(ctx context.Context, arg UpdateStage5try1CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage5try1FinishFailed(ctx context.Context, arg UpdateStage5try1FinishFailedParams) error
	// (scorer role)
	UpdateStage5try1FinishSuccess(ctx context.Context, arg UpdateStage5try1FinishSuccessParams) error
	// (scorer role)
	UpdateStage5try1NextNo(ctx context.Context, arg UpdateStage5try1NextNoParams) error
	// (scorer role)
	UpdateStage5try1No1(ctx context.Context, arg UpdateStage5try1No1Params) (string, error)
	// (scorer role)
	UpdateStage5try1No2(ctx context.Context, arg UpdateStage5try1No2Params) (string, error)
	// (admin-super role)
	UpdateStage5try2(ctx context.Context, arg UpdateStage5try2Params) (UpdateStage5try2Row, error)
	// (scorer role)
	UpdateStage5try2Checkmarks(ctx context.Context, arg UpdateStage5try2CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage5try2FinishFailed(ctx context.Context, arg UpdateStage5try2FinishFailedParams) error
	// (scorer role)
	UpdateStage5try2FinishSuccess(ctx context.Context, arg UpdateStage5try2FinishSuccessParams) error
	// (scorer role)
	UpdateStage5try2NextNo(ctx context.Context, arg UpdateStage5try2NextNoParams) error
	// (scorer role)
	UpdateStage5try2No1(ctx context.Context, arg UpdateStage5try2No1Params) (string, error)
	// (scorer role)
	UpdateStage5try2No2(ctx context.Context, arg UpdateStage5try2No2Params) (string, error)
	// (scorer role)
	UpdateStage6NextTry(ctx context.Context, id pgtype.UUID) error
	// (admin-super role)
	UpdateStage6Signs(ctx context.Context, arg UpdateStage6SignsParams) (UpdateStage6SignsRow, error)
	// (admin-super role)
	UpdateStage6try1(ctx context.Context, arg UpdateStage6try1Params) (UpdateStage6try1Row, error)
	// (scorer role)
	UpdateStage6try1Checkmarks(ctx context.Context, arg UpdateStage6try1CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage6try1FinishFailed(ctx context.Context, arg UpdateStage6try1FinishFailedParams) error
	// (scorer role)
	UpdateStage6try1FinishSuccess(ctx context.Context, arg UpdateStage6try1FinishSuccessParams) error
	// (scorer role)
	UpdateStage6try1NextNo(ctx context.Context, arg UpdateStage6try1NextNoParams) error
	// (scorer role)
	UpdateStage6try1No1(ctx context.Context, arg UpdateStage6try1No1Params) (string, error)
	// (scorer role)
	UpdateStage6try1No2(ctx context.Context, arg UpdateStage6try1No2Params) (string, error)
	// (scorer role)
	UpdateStage6try1No3(ctx context.Context, arg UpdateStage6try1No3Params) (string, error)
	// (admin-super role)
	UpdateStage6try2(ctx context.Context, arg UpdateStage6try2Params) (UpdateStage6try2Row, error)
	// (scorer role)
	UpdateStage6try2Checkmarks(ctx context.Context, arg UpdateStage6try2CheckmarksParams) (string, error)
	// (scorer role)
	UpdateStage6try2FinishFailed(ctx context.Context, arg UpdateStage6try2FinishFailedParams) error
	// (scorer role)
	UpdateStage6try2FinishSuccess(ctx context.Context, arg UpdateStage6try2FinishSuccessParams) error
	// (scorer role)
	UpdateStage6try2NextNo(ctx context.Context, arg UpdateStage6try2NextNoParams) error
	// (scorer role)
	UpdateStage6try2No1(ctx context.Context, arg UpdateStage6try2No1Params) (string, error)
	// (scorer role)
	UpdateStage6try2No2(ctx context.Context, arg UpdateStage6try2No2Params) (string, error)
	// (scorer role)
	UpdateStage6try2No3(ctx context.Context, arg UpdateStage6try2No3Params) (string, error)
}

var _ Querier = (*Queries)(nil)
