// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: scorers.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScorer = `-- name: CreateScorer :one
WITH added_user AS (
  INSERT INTO users (username, password, name)
  VALUES ($2, $3, $4)
  RETURNING id, username, password, name, created_at, updated_at
), added_scorer AS (
  INSERT INTO scorers (user_id, exam_id, image_path)
  SELECT id, $1, COALESCE($5::text,'default.png') FROM added_user
  RETURNING id, user_id, exam_id, image_path
)
SELECT added_scorer.id, user_id, exam_id, username, name, image_path, created_at, updated_at 
FROM added_user, added_scorer
`

type CreateScorerParams struct {
	ExamID    pgtype.UUID
	Username  string
	Password  string
	Name      string
	ImagePath pgtype.Text
}

type CreateScorerRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExamID    pgtype.UUID
	Username  string
	Name      string
	ImagePath string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

// untuk ngebuat scorer (admin-super role) TODO: return sebanyak get scorer by id
func (q *Queries) CreateScorer(ctx context.Context, arg CreateScorerParams) (CreateScorerRow, error) {
	row := q.db.QueryRow(ctx, createScorer,
		arg.ExamID,
		arg.Username,
		arg.Password,
		arg.Name,
		arg.ImagePath,
	)
	var i CreateScorerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Username,
		&i.Name,
		&i.ImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllScorers = `-- name: GetAllScorers :many
SELECT exams.name AS exam, users.name AS name, image_path FROM scorers 
INNER JOIN users ON scorers.user_id = users.id
INNER JOIN exams ON scorers.exam_id = exams.id
`

type GetAllScorersRow struct {
	Exam      string
	Name      string
	ImagePath string
}

// untuk ngambil data display seluruh scorer (all role)
func (q *Queries) GetAllScorers(ctx context.Context) ([]GetAllScorersRow, error) {
	rows, err := q.db.Query(ctx, getAllScorers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllScorersRow
	for rows.Next() {
		var i GetAllScorersRow
		if err := rows.Scan(&i.Exam, &i.Name, &i.ImagePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScorerById = `-- name: GetScorerById :one
SELECT scorers.id, user_id, exam_id, username, name, image_path, created_at, updated_at FROM scorers
INNER JOIN users ON scorers.user_id = users.id
WHERE scorers.id = $1
`

type GetScorerByIdRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExamID    pgtype.UUID
	Username  string
	Name      string
	ImagePath string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

// untuk ngambil data akun scorer berdasarkan id (admin-super role)
func (q *Queries) GetScorerById(ctx context.Context, id pgtype.UUID) (GetScorerByIdRow, error) {
	row := q.db.QueryRow(ctx, getScorerById, id)
	var i GetScorerByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Username,
		&i.Name,
		&i.ImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScorerByUsername = `-- name: GetScorerByUsername :one
SELECT scorers.id, user_id, exam_id, username, password, users.name, image_path, active, users.created_at, users.updated_at FROM users
INNER JOIN scorers ON scorers.user_id = users.id
INNER JOIN exams ON scorers.exam_id = exams.id
WHERE username = $1
`

type GetScorerByUsernameRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExamID    pgtype.UUID
	Username  string
	Password  string
	Name      string
	ImagePath string
	Active    bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

// untuk ngambil data display scorer berdasarkan username (scorer role)
func (q *Queries) GetScorerByUsername(ctx context.Context, username string) (GetScorerByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getScorerByUsername, username)
	var i GetScorerByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.ImagePath,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScorerRelationById = `-- name: GetScorerRelationById :one
SELECT scorers.id, user_id, exam_id FROM scorers 
INNER JOIN users ON scorers.user_id = users.id
WHERE scorers.id = $1
`

type GetScorerRelationByIdRow struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	ExamID pgtype.UUID
}

// untuk ngambil data relasi scorer berdasarkan id (all role)
func (q *Queries) GetScorerRelationById(ctx context.Context, id pgtype.UUID) (GetScorerRelationByIdRow, error) {
	row := q.db.QueryRow(ctx, getScorerRelationById, id)
	var i GetScorerRelationByIdRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExamID)
	return i, err
}

const getScorerRelationByUserId = `-- name: GetScorerRelationByUserId :one
SELECT scorers.id, user_id, exam_id, active FROM scorers 
INNER JOIN users ON scorers.user_id = users.id
INNER JOIN exams ON scorers.exam_id = exams.id
WHERE user_id = $1
`

type GetScorerRelationByUserIdRow struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	ExamID pgtype.UUID
	Active bool
}

// untuk ngambil data relasi scorer berdasarkan user id (all role)
func (q *Queries) GetScorerRelationByUserId(ctx context.Context, userID pgtype.UUID) (GetScorerRelationByUserIdRow, error) {
	row := q.db.QueryRow(ctx, getScorerRelationByUserId, userID)
	var i GetScorerRelationByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Active,
	)
	return i, err
}

const getScorersByExamId = `-- name: GetScorersByExamId :many
SELECT scorers.id, name, image_path FROM scorers 
INNER JOIN users ON scorers.user_id = users.id
WHERE exam_id = $1
`

type GetScorersByExamIdRow struct {
	ID        pgtype.UUID
	Name      string
	ImagePath string
}

// untuk ngambil data akun seluruh scorer dalam satu exam (admin-super role)
func (q *Queries) GetScorersByExamId(ctx context.Context, examID pgtype.UUID) ([]GetScorersByExamIdRow, error) {
	rows, err := q.db.Query(ctx, getScorersByExamId, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScorersByExamIdRow
	for rows.Next() {
		var i GetScorersByExamIdRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ImagePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScorer = `-- name: UpdateScorer :one
WITH updated_user AS (
  UPDATE users 
  SET username = $2, password = COALESCE($4::text,password), name = $3, updated_at = NOW() 
  WHERE users.id = (
    SELECT user_id FROM scorers 
    WHERE scorers.id = $1
  )
  RETURNING id, username, name, created_at, updated_at
)
SELECT scorers.id, user_id, exam_id, username, name, image_path, created_at, updated_at FROM scorers
INNER JOIN updated_user ON scorers.user_id = updated_user.id
WHERE scorers.id = $1
`

type UpdateScorerParams struct {
	ID       pgtype.UUID
	Username string
	Name     string
	Password pgtype.Text
}

type UpdateScorerRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExamID    pgtype.UUID
	Username  string
	Name      string
	ImagePath string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

// untuk update data akun admin (super role) TODO: return sebanyak get admin by id
func (q *Queries) UpdateScorer(ctx context.Context, arg UpdateScorerParams) (UpdateScorerRow, error) {
	row := q.db.QueryRow(ctx, updateScorer,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Password,
	)
	var i UpdateScorerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExamID,
		&i.Username,
		&i.Name,
		&i.ImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScorerImage = `-- name: UpdateScorerImage :one
WITH updated_user AS (
  UPDATE users 
  SET updated_at = NOW() 
  WHERE users.id = (
    SELECT user_id FROM scorers 
    WHERE scorers.id = $1
  )
)
UPDATE scorers
SET image_path = $2
WHERE scorers.id = $1
RETURNING image_path
`

type UpdateScorerImageParams struct {
	ID        pgtype.UUID
	ImagePath string
}

// untuk mengupdate foto scorer berdasarkan id (all role)
func (q *Queries) UpdateScorerImage(ctx context.Context, arg UpdateScorerImageParams) (string, error) {
	row := q.db.QueryRow(ctx, updateScorerImage, arg.ID, arg.ImagePath)
	var image_path string
	err := row.Scan(&image_path)
	return image_path, err
}
