// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: stage0.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStage0 = `-- name: CreateStage0 :one
INSERT INTO stage0_results (result_id)
VALUES ($1)
RETURNING id, result_id, status, series1, series2, series3, series4, series5, checkmarks, shooter_sign, scorer_sign, created_at, updated_at
`

func (q *Queries) CreateStage0(ctx context.Context, resultID pgtype.UUID) (Stage0Result, error) {
	row := q.db.QueryRow(ctx, createStage0, resultID)
	var i Stage0Result
	err := row.Scan(
		&i.ID,
		&i.ResultID,
		&i.Status,
		&i.Series1,
		&i.Series2,
		&i.Series3,
		&i.Series4,
		&i.Series5,
		&i.Checkmarks,
		&i.ShooterSign,
		&i.ScorerSign,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStage0 = `-- name: DeleteStage0 :exec
WITH deleted_stage0 AS (
  DELETE FROM stage0_results
  WHERE stage0_results.id = $1
  RETURNING result_id
)
UPDATE results 
SET stage = '0', updated_at = NOW()
WHERE id = (SELECT result_id FROM deleted_stage0)
`

// (admin-super role)
func (q *Queries) DeleteStage0(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStage0, id)
	return err
}

const getStage0ById = `-- name: GetStage0ById :one
SELECT 
  stage0_results.id, 
  stage0_results.result_id, 
  stage0_results.status, 
  stage0_results.series1, 
  stage0_results.series2, 
  stage0_results.series3, 
  stage0_results.series4, 
  stage0_results.series5,
  stage0_results.checkmarks,
  stage0_results.shooter_sign,
  stage0_results.scorer_sign,
  stage0_results.created_at,
  stage0_results.updated_at
FROM stage0_results
WHERE stage0_results.id = $1
`

func (q *Queries) GetStage0ById(ctx context.Context, id pgtype.UUID) (Stage0Result, error) {
	row := q.db.QueryRow(ctx, getStage0ById, id)
	var i Stage0Result
	err := row.Scan(
		&i.ID,
		&i.ResultID,
		&i.Status,
		&i.Series1,
		&i.Series2,
		&i.Series3,
		&i.Series4,
		&i.Series5,
		&i.Checkmarks,
		&i.ShooterSign,
		&i.ScorerSign,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStage0RelationByResultId = `-- name: GetStage0RelationByResultId :one
SELECT 
  stage0_results.id, 
  stage0_results.result_id
FROM stage0_results
WHERE stage0_results.result_id = $1
`

type GetStage0RelationByResultIdRow struct {
	ID       pgtype.UUID
	ResultID pgtype.UUID
}

func (q *Queries) GetStage0RelationByResultId(ctx context.Context, resultID pgtype.UUID) (GetStage0RelationByResultIdRow, error) {
	row := q.db.QueryRow(ctx, getStage0RelationByResultId, resultID)
	var i GetStage0RelationByResultIdRow
	err := row.Scan(&i.ID, &i.ResultID)
	return i, err
}

const getStage0Status = `-- name: GetStage0Status :one
SELECT 
  stage0_results.status
FROM stage0_results
WHERE stage0_results.id = $1
`

func (q *Queries) GetStage0Status(ctx context.Context, id pgtype.UUID) (Stage0Status, error) {
	row := q.db.QueryRow(ctx, getStage0Status, id)
	var status Stage0Status
	err := row.Scan(&status)
	return status, err
}

const updateResultNextStage = `-- name: UpdateResultNextStage :exec
UPDATE results 
SET stage = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateResultNextStageParams struct {
	ID    pgtype.UUID
	Stage Stages
}

// (scorer role) dibuat by id, utk update stage
func (q *Queries) UpdateResultNextStage(ctx context.Context, arg UpdateResultNextStageParams) error {
	_, err := q.db.Exec(ctx, updateResultNextStage, arg.ID, arg.Stage)
	return err
}

const updateStage0 = `-- name: UpdateStage0 :one
UPDATE stage0_results
SET 
  status = $2, 
  series1 = $3, 
  series2 = $4,
  series3 = $5,
  series4 = $6,
  series5 = $7,
  checkmarks = $8,
  updated_at = NOW()
WHERE id = $1 
RETURNING id, result_id, status, series1, series2, series3, series4, series5, checkmarks, created_at, updated_at
`

type UpdateStage0Params struct {
	ID         pgtype.UUID
	Status     Stage0Status
	Series1    string
	Series2    string
	Series3    string
	Series4    string
	Series5    string
	Checkmarks string
}

type UpdateStage0Row struct {
	ID         pgtype.UUID
	ResultID   pgtype.UUID
	Status     Stage0Status
	Series1    string
	Series2    string
	Series3    string
	Series4    string
	Series5    string
	Checkmarks string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

// (admin-super role)
func (q *Queries) UpdateStage0(ctx context.Context, arg UpdateStage0Params) (UpdateStage0Row, error) {
	row := q.db.QueryRow(ctx, updateStage0,
		arg.ID,
		arg.Status,
		arg.Series1,
		arg.Series2,
		arg.Series3,
		arg.Series4,
		arg.Series5,
		arg.Checkmarks,
	)
	var i UpdateStage0Row
	err := row.Scan(
		&i.ID,
		&i.ResultID,
		&i.Status,
		&i.Series1,
		&i.Series2,
		&i.Series3,
		&i.Series4,
		&i.Series5,
		&i.Checkmarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStage0Checkmarks = `-- name: UpdateStage0Checkmarks :one
UPDATE stage0_results
SET checkmarks = $2, updated_at = NOW()
WHERE id = $1 
RETURNING checkmarks
`

type UpdateStage0CheckmarksParams struct {
	ID         pgtype.UUID
	Checkmarks string
}

// (scorer role)
func (q *Queries) UpdateStage0Checkmarks(ctx context.Context, arg UpdateStage0CheckmarksParams) (string, error) {
	row := q.db.QueryRow(ctx, updateStage0Checkmarks, arg.ID, arg.Checkmarks)
	var checkmarks string
	err := row.Scan(&checkmarks)
	return checkmarks, err
}

const updateStage0FinishFailed = `-- name: UpdateStage0FinishFailed :exec
WITH updated_stage0 AS (
  UPDATE stage0_results
  SET status = '6', shooter_sign = $2, scorer_sign = $3, updated_at = NOW()
  WHERE stage0_results.id = $1
  RETURNING result_id
)
UPDATE results
SET failed = true, updated_at = NOW()
WHERE id = (SELECT result_id FROM updated_stage0)
`

type UpdateStage0FinishFailedParams struct {
	ID          pgtype.UUID
	ShooterSign pgtype.Text
	ScorerSign  pgtype.Text
}

// (scorer role)
func (q *Queries) UpdateStage0FinishFailed(ctx context.Context, arg UpdateStage0FinishFailedParams) error {
	_, err := q.db.Exec(ctx, updateStage0FinishFailed, arg.ID, arg.ShooterSign, arg.ScorerSign)
	return err
}

const updateStage0FinishSuccess = `-- name: UpdateStage0FinishSuccess :exec
WITH  updated_stage0 AS (
  UPDATE stage0_results
  SET status = '6', shooter_sign = $2, scorer_sign = $3, updated_at = NOW()
  WHERE stage0_results.id = $1
  RETURNING result_id
)
UPDATE results
SET stage = '1', updated_at = NOW()
WHERE id = (SELECT result_id FROM updated_stage0)
`

type UpdateStage0FinishSuccessParams struct {
	ID          pgtype.UUID
	ShooterSign pgtype.Text
	ScorerSign  pgtype.Text
}

// (scorer role)
func (q *Queries) UpdateStage0FinishSuccess(ctx context.Context, arg UpdateStage0FinishSuccessParams) error {
	_, err := q.db.Exec(ctx, updateStage0FinishSuccess, arg.ID, arg.ShooterSign, arg.ScorerSign)
	return err
}

const updateStage0NextSeries = `-- name: UpdateStage0NextSeries :exec
UPDATE stage0_results
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateStage0NextSeriesParams struct {
	ID     pgtype.UUID
	Status Stage0Status
}

// (scorer role)
func (q *Queries) UpdateStage0NextSeries(ctx context.Context, arg UpdateStage0NextSeriesParams) error {
	_, err := q.db.Exec(ctx, updateStage0NextSeries, arg.ID, arg.Status)
	return err
}

const updateStage0Series1 = `-- name: UpdateStage0Series1 :one
UPDATE stage0_results
SET series1 = $2, updated_at = NOW()
WHERE id = $1
RETURNING series1
`

type UpdateStage0Series1Params struct {
	ID      pgtype.UUID
	Series1 string
}

// (scorer role)
func (q *Queries) UpdateStage0Series1(ctx context.Context, arg UpdateStage0Series1Params) (string, error) {
	row := q.db.QueryRow(ctx, updateStage0Series1, arg.ID, arg.Series1)
	var series1 string
	err := row.Scan(&series1)
	return series1, err
}

const updateStage0Series2 = `-- name: UpdateStage0Series2 :one
UPDATE stage0_results
SET series2 = $2, updated_at = NOW()
WHERE id = $1
RETURNING series2
`

type UpdateStage0Series2Params struct {
	ID      pgtype.UUID
	Series2 string
}

// (scorer role)
func (q *Queries) UpdateStage0Series2(ctx context.Context, arg UpdateStage0Series2Params) (string, error) {
	row := q.db.QueryRow(ctx, updateStage0Series2, arg.ID, arg.Series2)
	var series2 string
	err := row.Scan(&series2)
	return series2, err
}

const updateStage0Series3 = `-- name: UpdateStage0Series3 :one
UPDATE stage0_results
SET series3 = $2, updated_at = NOW()
WHERE id = $1
RETURNING series3
`

type UpdateStage0Series3Params struct {
	ID      pgtype.UUID
	Series3 string
}

// (scorer role)
func (q *Queries) UpdateStage0Series3(ctx context.Context, arg UpdateStage0Series3Params) (string, error) {
	row := q.db.QueryRow(ctx, updateStage0Series3, arg.ID, arg.Series3)
	var series3 string
	err := row.Scan(&series3)
	return series3, err
}

const updateStage0Series4 = `-- name: UpdateStage0Series4 :one
UPDATE stage0_results
SET series4 = $2, updated_at = NOW()
WHERE id = $1 
RETURNING series4
`

type UpdateStage0Series4Params struct {
	ID      pgtype.UUID
	Series4 string
}

// (scorer role)
func (q *Queries) UpdateStage0Series4(ctx context.Context, arg UpdateStage0Series4Params) (string, error) {
	row := q.db.QueryRow(ctx, updateStage0Series4, arg.ID, arg.Series4)
	var series4 string
	err := row.Scan(&series4)
	return series4, err
}

const updateStage0Series5 = `-- name: UpdateStage0Series5 :one
UPDATE stage0_results
SET series5 = $2, updated_at = NOW()
WHERE id = $1 
RETURNING series5
`

type UpdateStage0Series5Params struct {
	ID      pgtype.UUID
	Series5 string
}

// (scorer role)
func (q *Queries) UpdateStage0Series5(ctx context.Context, arg UpdateStage0Series5Params) (string, error) {
	row := q.db.QueryRow(ctx, updateStage0Series5, arg.ID, arg.Series5)
	var series5 string
	err := row.Scan(&series5)
	return series5, err
}

const updateStage0Signs = `-- name: UpdateStage0Signs :one
UPDATE stage0_results
SET 
  shooter_sign = $2, 
  scorer_sign = $3, 
  updated_at = NOW()
WHERE id = $1
RETURNING shooter_sign, scorer_sign, updated_at
`

type UpdateStage0SignsParams struct {
	ID          pgtype.UUID
	ShooterSign pgtype.Text
	ScorerSign  pgtype.Text
}

type UpdateStage0SignsRow struct {
	ShooterSign pgtype.Text
	ScorerSign  pgtype.Text
	UpdatedAt   pgtype.Timestamp
}

// (admin-super role)
func (q *Queries) UpdateStage0Signs(ctx context.Context, arg UpdateStage0SignsParams) (UpdateStage0SignsRow, error) {
	row := q.db.QueryRow(ctx, updateStage0Signs, arg.ID, arg.ShooterSign, arg.ScorerSign)
	var i UpdateStage0SignsRow
	err := row.Scan(&i.ShooterSign, &i.ScorerSign, &i.UpdatedAt)
	return i, err
}
