// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: stage0.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStage0 = `-- name: CreateStage0 :one
WITH added_stage0 AS (
  INSERT INTO stage0_results (result_id)
  VALUES ($1)
  RETURNING id, result_id, status, series1, series2, series3, series4, series5, created_at, updated_at
), updated_result AS (
  UPDATE results
  SET stage = '0', updated_at = NOW()
  WHERE id = $1
)
SELECT 
  added_stage0.id, 
  added_stage0.result_id, 
  added_stage0.status, 
  added_stage0.series1, 
  added_stage0.series2, 
  added_stage0.series3, 
  added_stage0.series4, 
  added_stage0.series5, 
  added_stage0.created_at, 
  added_stage0.updated_at
FROM added_stage0
`

type CreateStage0Row struct {
	ID        pgtype.UUID
	ResultID  pgtype.UUID
	Status    interface{}
	Series1   interface{}
	Series2   interface{}
	Series3   interface{}
	Series4   interface{}
	Series5   interface{}
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreateStage0(ctx context.Context, resultID pgtype.UUID) (CreateStage0Row, error) {
	row := q.db.QueryRow(ctx, createStage0, resultID)
	var i CreateStage0Row
	err := row.Scan(
		&i.ID,
		&i.ResultID,
		&i.Status,
		&i.Series1,
		&i.Series2,
		&i.Series3,
		&i.Series4,
		&i.Series5,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStage0 = `-- name: GetStage0 :one
SELECT 
  stage0_results.id, 
  stage0_results.result_id, 
  stage0_results.status, 
  stage0_results.series1, 
  stage0_results.series2, 
  stage0_results.series3, 
  stage0_results.series4, 
  stage0_results.series5
FROM stage0_results
WHERE stage0_results.result_id = $1
`

type GetStage0Row struct {
	ID       pgtype.UUID
	ResultID pgtype.UUID
	Status   interface{}
	Series1  interface{}
	Series2  interface{}
	Series3  interface{}
	Series4  interface{}
	Series5  interface{}
}

func (q *Queries) GetStage0(ctx context.Context, resultID pgtype.UUID) (GetStage0Row, error) {
	row := q.db.QueryRow(ctx, getStage0, resultID)
	var i GetStage0Row
	err := row.Scan(
		&i.ID,
		&i.ResultID,
		&i.Status,
		&i.Series1,
		&i.Series2,
		&i.Series3,
		&i.Series4,
		&i.Series5,
	)
	return i, err
}

const updateStage0NextSeries2 = `-- name: UpdateStage0NextSeries2 :one
UPDATE stage0_results
SET series1 = $2, status = 2, updated_at = NOW()
WHERE result_id = $1 
RETURNING series1, status
`

type UpdateStage0NextSeries2Params struct {
	ResultID pgtype.UUID
	Series1  interface{}
}

type UpdateStage0NextSeries2Row struct {
	Series1 interface{}
	Status  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0NextSeries2(ctx context.Context, arg UpdateStage0NextSeries2Params) (UpdateStage0NextSeries2Row, error) {
	row := q.db.QueryRow(ctx, updateStage0NextSeries2, arg.ResultID, arg.Series1)
	var i UpdateStage0NextSeries2Row
	err := row.Scan(&i.Series1, &i.Status)
	return i, err
}

const updateStage0NextSeries3 = `-- name: UpdateStage0NextSeries3 :one
UPDATE stage0_results
SET series2 = $2, status = 3, updated_at = NOW()
WHERE result_id = $1 
RETURNING series2, status
`

type UpdateStage0NextSeries3Params struct {
	ResultID pgtype.UUID
	Series2  interface{}
}

type UpdateStage0NextSeries3Row struct {
	Series2 interface{}
	Status  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0NextSeries3(ctx context.Context, arg UpdateStage0NextSeries3Params) (UpdateStage0NextSeries3Row, error) {
	row := q.db.QueryRow(ctx, updateStage0NextSeries3, arg.ResultID, arg.Series2)
	var i UpdateStage0NextSeries3Row
	err := row.Scan(&i.Series2, &i.Status)
	return i, err
}

const updateStage0NextSeries4 = `-- name: UpdateStage0NextSeries4 :one
UPDATE stage0_results
SET series3 = $2, status = 4, updated_at = NOW()
WHERE result_id = $1 
RETURNING series3, status
`

type UpdateStage0NextSeries4Params struct {
	ResultID pgtype.UUID
	Series3  interface{}
}

type UpdateStage0NextSeries4Row struct {
	Series3 interface{}
	Status  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0NextSeries4(ctx context.Context, arg UpdateStage0NextSeries4Params) (UpdateStage0NextSeries4Row, error) {
	row := q.db.QueryRow(ctx, updateStage0NextSeries4, arg.ResultID, arg.Series3)
	var i UpdateStage0NextSeries4Row
	err := row.Scan(&i.Series3, &i.Status)
	return i, err
}

const updateStage0NextSeries5 = `-- name: UpdateStage0NextSeries5 :one
UPDATE stage0_results
SET series4 = $2, status = 5, updated_at = NOW()
WHERE result_id = $1 
RETURNING series4, status
`

type UpdateStage0NextSeries5Params struct {
	ResultID pgtype.UUID
	Series4  interface{}
}

type UpdateStage0NextSeries5Row struct {
	Series4 interface{}
	Status  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0NextSeries5(ctx context.Context, arg UpdateStage0NextSeries5Params) (UpdateStage0NextSeries5Row, error) {
	row := q.db.QueryRow(ctx, updateStage0NextSeries5, arg.ResultID, arg.Series4)
	var i UpdateStage0NextSeries5Row
	err := row.Scan(&i.Series4, &i.Status)
	return i, err
}

const updateStage0NextSeries6 = `-- name: UpdateStage0NextSeries6 :one
UPDATE stage0_results
SET series5 = $2, status = 6, updated_at = NOW()
WHERE result_id = $1 
RETURNING series5, status
`

type UpdateStage0NextSeries6Params struct {
	ResultID pgtype.UUID
	Series5  interface{}
}

type UpdateStage0NextSeries6Row struct {
	Series5 interface{}
	Status  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0NextSeries6(ctx context.Context, arg UpdateStage0NextSeries6Params) (UpdateStage0NextSeries6Row, error) {
	row := q.db.QueryRow(ctx, updateStage0NextSeries6, arg.ResultID, arg.Series5)
	var i UpdateStage0NextSeries6Row
	err := row.Scan(&i.Series5, &i.Status)
	return i, err
}

const updateStage0Series1 = `-- name: UpdateStage0Series1 :one
UPDATE stage0_results
SET series1 = $2, updated_at = NOW()
WHERE result_id = $1
RETURNING series1
`

type UpdateStage0Series1Params struct {
	ResultID pgtype.UUID
	Series1  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0Series1(ctx context.Context, arg UpdateStage0Series1Params) (interface{}, error) {
	row := q.db.QueryRow(ctx, updateStage0Series1, arg.ResultID, arg.Series1)
	var series1 interface{}
	err := row.Scan(&series1)
	return series1, err
}

const updateStage0Series2 = `-- name: UpdateStage0Series2 :one
UPDATE stage0_results
SET series2 = $2, updated_at = NOW()
WHERE result_id = $1
RETURNING series2
`

type UpdateStage0Series2Params struct {
	ResultID pgtype.UUID
	Series2  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0Series2(ctx context.Context, arg UpdateStage0Series2Params) (interface{}, error) {
	row := q.db.QueryRow(ctx, updateStage0Series2, arg.ResultID, arg.Series2)
	var series2 interface{}
	err := row.Scan(&series2)
	return series2, err
}

const updateStage0Series3 = `-- name: UpdateStage0Series3 :one
UPDATE stage0_results
SET series3 = $2, updated_at = NOW()
WHERE result_id = $1
RETURNING series3
`

type UpdateStage0Series3Params struct {
	ResultID pgtype.UUID
	Series3  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0Series3(ctx context.Context, arg UpdateStage0Series3Params) (interface{}, error) {
	row := q.db.QueryRow(ctx, updateStage0Series3, arg.ResultID, arg.Series3)
	var series3 interface{}
	err := row.Scan(&series3)
	return series3, err
}

const updateStage0Series4 = `-- name: UpdateStage0Series4 :one
UPDATE stage0_results
SET series4 = $2, updated_at = NOW()
WHERE result_id = $1 
RETURNING series4
`

type UpdateStage0Series4Params struct {
	ResultID pgtype.UUID
	Series4  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0Series4(ctx context.Context, arg UpdateStage0Series4Params) (interface{}, error) {
	row := q.db.QueryRow(ctx, updateStage0Series4, arg.ResultID, arg.Series4)
	var series4 interface{}
	err := row.Scan(&series4)
	return series4, err
}

const updateStage0Series5 = `-- name: UpdateStage0Series5 :one
UPDATE stage0_results
SET series5 = $2, updated_at = NOW()
WHERE result_id = $1 
RETURNING series5
`

type UpdateStage0Series5Params struct {
	ResultID pgtype.UUID
	Series5  interface{}
}

// (scorer role)
func (q *Queries) UpdateStage0Series5(ctx context.Context, arg UpdateStage0Series5Params) (interface{}, error) {
	row := q.db.QueryRow(ctx, updateStage0Series5, arg.ResultID, arg.Series5)
	var series5 interface{}
	err := row.Scan(&series5)
	return series5, err
}
