// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: supers.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSuperByUsername = `-- name: GetSuperByUsername :one
SELECT supers.id, user_id, username, password, name FROM users
INNER JOIN supers ON supers.user_id = users.id
WHERE username = $1
`

type GetSuperByUsernameRow struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	Username string
	Password string
	Name     string
}

func (q *Queries) GetSuperByUsername(ctx context.Context, username string) (GetSuperByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getSuperByUsername, username)
	var i GetSuperByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Name,
	)
	return i, err
}
