// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

// dipake untuk delete user
func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id FROM users
WHERE username = $1
`

// dipake untuk mengecek username ketika create user baru
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
